### ISSUE TITLE
Confusion !

### ISSUE THREAD

**Issue by karopass** [sujithkanna/SmileyRating#4]
I am little confused in this library. Its looking great and I am planning to integrate in my applications. I have doubt that how can I set threshold for go market as well launching time ? like I need to show this dialogue on 5th launch of application ?

**Comment by sujithkanna** [comment]
### SmileyRating in dialog
```java
    SmileRating mSmileRating = new SmileRating(context);
    Dialog dialog = new Dialog(context);
    dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
    dialog.setContentView(mSmileRating);
    mSmileRating.setOnSmileySelectionListener(yourListener);
    mSmileRating.setOnRatingSelectedListener(yourListener1);
    mSmileRating.setSelectedSmile(BaseRating.GREAT);
    dialog.show();
```
This is an example of how to implement smiley rating in a dialog. (*Not the entire solution*).

```java
dialog.setContentView(mSmileRating);
```
here instead of creating a new smileyrating instance, place the SmileyRating in a xml layout you create for the dialog, then inflate and set the inflated layout into the dialog.0

To open the dialog when the user opens the app for the fifth time is not the part of the SmileyRating. But I can give you some advice how to do that also. In the first screen of your activity, store and icrement an int in sharedpreferences. Then you can check your app is opened how many timmes and you can then decide to show the rating dialog.

I hope this helps you.
