### ISSUE TITLE
Allow changable Text color

### ISSUE THREAD

**Issue by Techwolf12** [sujithkanna/SmileyRating#5]
Hi! 

First of all, thanks for your work in this! 
A slight improvement might be making the text color a variable as well. 
I will make a pull request for this somewhere this week!

Edit: It seems to be documented but non functional?

**Comment by sujithkanna** [comment]
Thank you very much :) Pull Requests are always welcomed.

What and where it was not working? can you specify clearly, so that I can also look into  it. I ran the application and used color change api, It is working fine here. So please give me the case where it is not working. That would be helpful. Thank you :)

**Comment by Techwolf12** [comment]
Hi! Issue was an old version, fixed now, my bad! Thanks for your time :)
